--USERS

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY,
	EMAIL VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	GENDER VARCHAR(6) NOT NULL,
	DOB VARCHAR(200) NOT NULL,
	DOJ VARCHAR(200) NOT NULL,
	PROFILE_IMAGE VARCHAR(50) NOT NULL,
	NO_OF_COMMENTS NUMBER(10) DEFAULT 0 NOT NULL,
	NO_OF_FORUMS NUMBER(10) DEFAULT 0 NOT NULL,
	NO_OF_JOBS NUMBER(10) DEFAULT 0 NOT NULL,
	NO_OF_EVENTS NUMBER(10) DEFAULT 0 NOT NULL,
	NO_OF_FRIENDS NUMBER(10) DEFAULT 0 NOT NULL,
	ISONLINE VARCHAR(5) DEFAULT 'FALSE' NOT NULL,
	ROLE VARCHAR(20) DEFAULT 'STUDENT' NOT NULL,
	STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL
);

--USER_SEQ

	CREATE SEQUENCE USERS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;
	
--MORE_DETAILS

CREATE TABLE MORE_DETAILS(

	ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	STREET VARCHAR(200),
	CITY VARCHAR(200),
	STATE VARCHAR(200),
	COUNTRY VARCHAR(200),
	ABOUT VARCHAR(500)

);

--MORE_DETAILS_SEQ

	CREATE SEQUENCE MORE_DETAILS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--SOCIAL_LINK

CREATE TABLE SOCIAL_LINKS(
	ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	BELONGS VARCHAR(200) NOT NULL,
	DETAIL VARCHAR(200) NOT NULL
);

--SOCIAL_LINK_SEQ

	CREATE SEQUENCE SOCIAL_LINKS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--EDUCATION DETAILS

CREATE TABLE EDUCATION_DETAILS(
	
	ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	UNIVERSITY VARCHAR(500) DEFAULT 'NA',
	UNIVERSITY_YEAR INT DEFAULT '0',
	HIGH_SCHOOL VARCHAR(500) DEFAULT 'NA',
	HIGH_SCHOOL_YEAR INT DEFAULT '0'

);

--SOCIAL_LINK_SEQ

	CREATE SEQUENCE EDUCATION_DETAILS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;
	
--BLOCK

CREATE TABLE BLOCK(

	ID INT PRIMARY KEY,
	BLOCK_TYPE VARCHAR(200) NOT NULL,
	INIATER_ID INT NOT NULL,
	INTIATER_NAME VARCHAR(200) NOT NULL,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL

);

--BLOCK_SEQ

	CREATE SEQUENCE BLOCK_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--BLOGS

CREATE TABLE BLOGS(
	BLOG_ID INT PRIMARY KEY,
	TITLE VARCHAR(50) NOT NULL,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(40) NOT NULL,
	DESCRIPTION CLOB NOT NULL,
	POST_DATE VARCHAR(100) NOT NULL,
	IMAGE_URL VARCHAR(200) NOT NULL,
	NO_OF_COMMENTS NUMBER(10) DEFAULT 0 NOT NULL,
	NO_OF_LIKES NUMBER(10) DEFAULT 0 NOT NULL,
	REPORT VARCHAR(50) DEFAULT 'NO',
	STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL
);

--BLOGS SEQUENCE
	
	CREATE SEQUENCE BLOGS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--BLOGS COMMENTS

CREATE TABLE BLOG_COMMENTS(
	BLOG_COMMENT_ID INT PRIMARY KEY,
	BLOG_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(40) NOT NULL,
	BLOG_COMMENT CLOB NOT NULL,
	COMMENT_DATE VARCHAR(50) NOT NULL,
	NO_OF_LIKES NUMBER(10) DEFAULT 0 NOT NULL,
	REPORT VARCHAR(10) DEFAULT 'NO'
);

--BLOG COMMENT SEQUENCE
CREATE SEQUENCE BLOG_COMMENTS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--BLOG_LIKES

CREATE TABLE BLOG_LIKES(

	ID INT PRIMARY KEY,
	BLOG_ID INT NOT NULL,
	BLOG_NAME VARCHAR(500) NOT NULL,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	DATE_TIME VARCHAR(50) NOT NULL
	
);

--TOPIC_LIKES_SEQ

	CREATE SEQUENCE BLOG_LIKES_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;


	
--FORUMS

CREATE TABLE FORUMS(
	FORUM_ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(40) NOT NULL,
	FORUM_NAME VARCHAR(50) NOT NULL,
	FORUM_DESCRIPTION VARCHAR(500) NOT NULL,
	CREATED_DATE VARCHAR(50) NOT NULL, 
	NO_OF_REQUEST INT DEFAULT '0' NOT NULL,
	IMAGE_URL VARCHAR(200) NOT NULL,
	NUMBER_OF_MEMBERS INT NOT NULL,
	NUMBER_OF_TOPICS INT NOT NULL,
	REPORT VARCHAR(10) DEFAULT 'NO' NOT NULL,
	STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL
);

--FORUMS_SEQ

  CREATE SEQUENCE FORUMS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;


--FORUM COMMENTS

CREATE TABLE FORUM_COMMENTS(
	FORUM_COMMENT_ID INT PRIMARY KEY,
	FORUM_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	FORUM_COMMENT CLOB NOT NULL,
	COMMENT_DATE TIMESTAMP NOT NULL 
);

--FORUM COMMENTS SEQUENCE
  CREATE SEQUENCE FORUM_COMMENTS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--FORUM REQUEST

CREATE TABLE FORUM_REQUESTS(
	REQUEST_ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(40) NOT NULL,
	FORUM_ID INT NOT NULL,
	REQUEST_DATE TIMESTAMP NOT NULL,
	STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL
);

--FORUM REQUEST SEQUENCE

	CREATE SEQUENCE FORUM_REQUEST_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--FORUM MEMBERS

CREATE TABLE FORUM_MEMBERS(

	ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	FORUM_ID INT NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL

);

--FORUM_MEMBERS_SEQ

	CREATE SEQUENCE FORUM_MEMBERS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--FORUM_ADMIN

CREATE TABLE FORUM_ADMINS(

	ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	FORUM_ID INT NOT NULL,
	FORUM_NAME VARCHAR(200) NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL

);

--FORUM_ADMINS_SEQ

	CREATE SEQUENCE FORUM_ADMINS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--TOPICS

CREATE TABLE TOPICS(
	TOPIC_ID INT PRIMARY KEY,
	USER_ID INT NOT NULL, 
	USER_NAME VARCHAR(40) NOT NULL, 
	FORUM_ID INT NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	IMAGE_URL VARCHAR(200) NOT NULL,
	DESCRIPTION CLOB NOT NULL,
	CREATED_DATE VARCHAR(50) NOT NULL,
	REPORT VARCHAR(10) DEFAULT 'NO',
	STATUS VARCHAR(10) DEFAULT 'OPEN' NOT NULL
);

--TOPICS SEQUENCE

	CREATE SEQUENCE TOPICS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--TOPIC_LIKES

CREATE TABLE TOPIC_LIKES(

	ID INT PRIMARY KEY,
	TOPIC_ID INT NOT NULL,
	TOPIC_NAME VARCHAR(500) NOT NULL,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL

);

--TOPIC_LIKES_SEQ

	CREATE SEQUENCE TOPIC_LIKES_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;


	
--FRIENDS

CREATE TABLE FRIENDS(
	ID INT PRIMARY KEY, 
	INITIATER_ID INT NOT NULL,
	FRIEND_ID INT NOT NULL,
	STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL
);

--FRIENDS SEQUENCE
	CREATE SEQUENCE FRIENDS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--JOBS

CREATE TABLE JOBS(
	JOB_ID INT PRIMARY KEY, 
	TITLE VARCHAR(200) NOT NULL,
	COMPANY VARCHAR(200) NOT NULL,
	EXPERIENCE INT NOT NULL,
	DESCRIPTION CLOB NOT NULL, 
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(40) NOT NULL,
	QUALIFICATION VARCHAR(200) NOT NULL,
	POST_DATE VARCHAR(50) NOT NULL,
	SALARY INT NOT NULL,
	KEYSKILLS VARCHAR(500) NOT NULL,
	LOCATION VARCHAR(100) NOT NULL,
	REPORT VARCHAR(10) DEFAULT 'NO' NOT NULL,
	STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL
);

--JOBS SEQUENCE
CREATE SEQUENCE JOBS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--JOB APPLIED

CREATE TABLE JOB_APPLIED(
	APPLIED_ID INT PRIMARY KEY,
	JOB_ID INT NOT NULL, 
	USER_ID INT NOT NULL, 
	USER_NAME VARCHAR(40) NOT NULL,
	APPLIED_DATE TIMESTAMP,
	STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL
);

--JOB APPLIED SEQUENCE
CREATE SEQUENCE JOB_APPLIED_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--EVENTS

CREATE TABLE EVENTS(
	EVENT_ID INT PRIMARY KEY, 
	USER_ID INT NOT NULL, 
	USER_NAME VARCHAR(40) NOT NULL,
	NAME VARCHAR(50) NOT NULL, 
	IMAGE_URL VARCHAR(200) NOT NULL,
	VENUE VARCHAR(500) NOT NULL, 
	DESCRIPTION CLOB NOT NULL,
	START_DATE VARCHAR(50) NOT NULL, 
	END_DATE VARCHAR(50) NOT NULL, 
	POST_DATE VARCHAR(50) NOT NULL,
	NO_OF_APPLIED INT DEFAULT '0',
	REPORTED VARCHAR(10) DEFAULT 'NO',
	EVENT_STATUS VARCHAR(20) DEFAULT 'COMING SOON',
	STATUS VARCHAR(10) DEFAULT 'PENDING' 
);

--EVENT SEQUENCE
CREATE SEQUENCE EVENTS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--EVENT_JOINED

CREATE TABLE EVENT_JOINED(
	JOINED_ID INT PRIMARY KEY,
	EVENT_ID INT NOT NULL, 
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(40) NOT NULL,
	STATUS VARCHAR(10) DEFAULT 'APPLIED' NOT NULL	
);	

--JOB APPLIED SEQUENCE
CREATE SEQUENCE EVENT_JOINED_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;
	
--INBOXES

CREATE TABLE INBOXES(

	ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	TOTAL_MESSAGES INT DEFAULT'0',
	UNREAD_MESSAGES INT DEFAULT'0',
	ARCHIVE_MESSAGES INT DEFAULT'0'

);

--INBOXES SEQUENCE

CREATE SEQUENCE INBOXES_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--THREAD

CREATE TABLE THREAD(

	ID INT PRIMARY KEY,
	THREAD_ID INT NOT NULL,
	FROM_USER_ID INT NOT NULL,
	TO_USER_ID INT NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL

);

--THREAD_SEQ

	CREATE SEQUENCE THREAD_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE TABLE MESSAGES(

	ID INT PRIMARY KEY,
	THREAD_ID INT NOT NULL,
	MESSAGE CLOB NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL,
	REPORT INT DEFAULT '0'

);

--PENALTIES

CREATE TABLE PENALTIES(

	ID INT PRIMARY KEY,
	INITIATER_ID INT NOT NULL,
	INITIATER_NAME VARCHAR(200) NOT NULL,
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL,
	REASON VARCHAR(1000) NOT NULL,
	DATE_TIME DATE NOT NULL

);

--PENALTIES SEQUENCE

CREATE SEQUENCE PENALTIES_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;
	
--REPORT TABLE

CREATE TABLE REPORTS(

	ID INT PRIMARY KEY,
	TYPE_OF_REPORT VARCHAR(200) NOT NULL,
	DATE_TIME VARCHAR(50) NOT NULL,
	DETAILS VARCHAR(1000),
	REPORTED_ID INT NOT NULL,
	COMMENT_ID INT
  
);

--REPORTS SEQUENCE

CREATE SEQUENCE REPORTS_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

--HANDLED TABLE

CREATE TABLE HANDLED(

	ID INT PRIMARY KEY,
	TYPE_OF_REPORT VARCHAR(200) NOT NULL,
	DATE_TIME VARCHAR(50) NOT NULL,
	DETAILS VARCHAR(1000),
	USER_ID VARCHAR(200),
	HANDLED_BY VARCHAR(100) NOT NULL,
  	REPORTED_ID INT NOT NULL,
	COMMENT_ID INT,
	STATUS VARCHAR(20) DEFAULT 'HANDLED'
	
);

--REPORTS SEQUENCE

CREATE SEQUENCE HANDLED_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;